### ISSUE TITLE
Error in grep(x, transactions$Category): invalid regular expression error

### ISSUE THREAD

**Issue by lifepillar** [esovetkin/ledger-plots#1]
Using the current master, if I try the command from the help

    ledger-plots -q "^assets: -X EUR"

on a file containing virtual transactions, like this one:

```
2017/01/02 * XYZ
    [Expenses:XYZ]           $3,00
    [Assets:Checking]
```

I get this error:

    Generating accounts tree...
    Error in grep(x, transactions$Category) :
      invalid regular expression '[Assets', reason 'Missing ']''
    Calls: lapply ... query.plot -> order -> sapply -> lapply -> FUN -> grep

**Comment by esovetkin** [comment]
Thanks for reporting that! I have fixed the problem, but it seems to me that virtual accounts has to be treated in plots in some special way.
